#!/bin/bash

export PATH="$PATH":/home/henrikq/depot_tools
export GYP_DEFINES="component=shared_library" 
export BUILD_TOOLCHAIN_SYSROOTS="/home/henrikq/sysroot"
export BUILD_FLAGS="--no-pkg"
export CHROMIUM_BUILDTOOLS_PATH="/home/henrikq/work/chromium/src/buildtools"
export OPERA_DEV_FLAGS="--show-component-extension-with-background-pages --show-component-extension-options --disable-update --webui-debug-mode"
export ICECC_PREFIX="/usr"
export LD_LIBRARY_PATH="/home/henrikq/work/chromium/src/out/Release/"

alias rundev="~/work/chromium/src/out/Release/opera-developer $OPERA_DEV_FLAGS"
alias rundevclean="rundev --user-data-dir=/home/henrikq/builds/profile_clean/$(date +%s)"
alias builddev="time ~/work/desktop/infra_build.py --target opera $BUILD_FLAGS"
alias builddevop="time ~/work/desktop/infra_build.py --target opera opautolib $BUILD_FLAGS"
alias pakdev="ninja -k0 -C ~/work/chromium/src/out/Release opera_pak xdisplaycheck"
#alias pakdev="time ~/work/desktop/infra_build.py --target opera_pak $BUILD_FLAG"
alias icemon="USE_SCHEDULER=henrikq-2.users.oslo.osa icemon -n oslo"
alias opera-developer2="opera-developer --user-data-dir=/home/henrikq/.config/opera-developer2/ --webui-debug-mode"

alias opc="killall -q ~/work/chromium/src/out/Release/opera-developer; op c"
alias opcr='opc && rundev &'
